### PR TITLE
FIX Use trustee instead of trustor to validate trust token

### LINKED ISSUE #250: wrong user extracted from Trust Token
According with this line
https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/lib/services/keystoneAuth.js#L233

pep is using trustor_user instead of trustee_user to validate an user when a trust token is provided.

According with Keystone Trust extension doc:
http://specs.openstack.org/openstack/keystone-specs/api/v3/identity-api-v3-os-trust-ext.html
rustor_user_id (string)

Represents the user who created the trust, and who’s authorization is being delegated.

trustee_user_id (string)

Represents the user who is capable of consuming the trust.

Pep log:

```
time=2015-06-24T10:22:07.623Z | lvl=DEBUG | corr=72dab139-e973-4305-b827-fc4c6bd68b9e | trans=72dab139-e973-4305-b827-fc4c6bd68b9e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Retrieving user from keystone: {"url":"http://localhost:5000/v3/auth/tokens","method":"GET","json":{},"headers":{"X-Auth-Token":"9ed86564e45a432b970989d2cfa98d2d","X-Subject-Token":"9c92bfd42b0141caa84dc7b52a06eb22"}}
time=2015-06-24T10:22:07.639Z | lvl=DEBUG | corr=72dab139-e973-4305-b827-fc4c6bd68b9e | trans=72dab139-e973-4305-b827-fc4c6bd68b9e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Keystone response retrieving user:
time=2015-06-24T10:22:07.639Z | lvl=DEBUG | corr=72dab139-e973-4305-b827-fc4c6bd68b9e | trans=72dab139-e973-4305-b827-fc4c6bd68b9e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Keystone response retrieving user:
 {"token":{"OS-TRUST:trust":{"impersonation":false,"trustee_user":{"id":"66d8ab78b5754a78a96cc08ce35df809"},"id":"7f65b4d03b3a4f2985247ed5172c4cb0","trustor_user":{"id":"30234dbf712644838bbd7202ad54405a"}},"methods":["password"],"roles":[{"id":"3c7e51da93dc484596c7f396f4a2d315","name":"1ec9ddc2fed54509be7ba60e4312cbb2#SubServiceAdmin"}],"expires_at":"2015-06-24T11:17:42.499796Z","project":{"domain":{"id":"1ec9ddc2fed54509be7ba60e4312cbb2","name":"smartcity"},"id":"87b6772af18c4947a102784372a8037b","name":"/Basuras"},"catalog":[],"extras":{},"user":{"domain":{"id":"default","name":"Default"},"id":"66d8ab78b5754a78a96cc08ce35df809","name":"iotagent"},"audit_ids":["rXSL0gCZQmCXoOSfPWOwPA"],"issued_at":"2015-06-24T10:17:42.499823Z"}}
```

trustee is 66d8ab78b5754a78a96cc08ce35df809
trustor is 30234dbf712644838bbd7202ad54405a
but

```
time=2015-06-24T10:22:07.653Z | lvl=DEBUG | corr=72dab139-e973-4305-b827-fc4c6bd68b9e | trans=72dab139-e973-4305-b827-fc4c6bd68b9e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Extracting roles for token: {"url":"http://localhost:5000/v3/role_assignments","method":"GET","qs":{"user.id":"30234dbf712644838bbd7202ad54405a","effective":true},"headers":{"X-Auth-Token":"9ed86564e45a432b970989d2cfa98d2d"}}
```

used user to extract roles is 30234dbf712644838bbd7202ad54405a -> trustor

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #250

### CODE REVIEW

**Comment by AlvaroVega** [comment]
It seems to me that not only change trustor by trustee user is enough to fix the bug, since extract roles now does not extract nothing, since trust behavior is not like assignment role behavior
```
time=2015-06-24T10:56:37.263Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Extracting roles for token: {"url":"http://localhost:5000/v3/role_assignments","method":"GET","qs":{"user.id":"66d8ab78b5754a78a96cc08ce35df809","effective":true},"headers":{"X-Auth-Token":"74ad28e1cd6b4ed5b57bb87258fa2cfd"}}
time=2015-06-24T10:56:37.284Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Keystone response retrieving roles:

 "{\"role_assignments\": [], \"links\": {\"self\": \"http://localhost:5000/v3/role_assignments?user.id=66d8ab78b5754a78a96cc08ce35df809&effective=true\", \"previous\": null, \"next\": null}}"
time=2015-06-24T10:56:37.284Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Roles response from Keystone: 
"{\"role_assignments\": [], \"links\": {\"self\": \"http://localhost:5000/v3/role_assignments?user.id=66d8ab78b5754a78a96cc08ce35df809&effective=true\", \"previous\": null, \"next\": null}}"


time=2015-06-24T10:56:37.285Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Getting roles from response for service [1ec9ddc2fed54509be7ba60e4312cbb2] and subservice [87b6772af18c4947a102784372a8037b]
time=2015-06-24T10:56:37.285Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Extracted roles: 
[]

time=2015-06-24T10:56:37.285Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=Roles not found for subservice /Basuras
time=2015-06-24T10:56:37.287Z | lvl=DEBUG | corr=2a2b2abc-82c8-4615-8cec-1eed99cac18e | trans=2a2b2abc-82c8-4615-8cec-1eed99cac18e | op=/v1/contextEntities?details=on&limit=15&offset=0 | msg=response-time: 133 statusCode: 401
```

**Comment by AlvaroVega** [comment]
the role that you need is already into trust, you do not need to extract it

**Comment by dmoranj** [comment]
The problem is not whether I need it or not but whether the current extraction mechanism will work when applied to trust tokens. If it works like that, we can use it as it is and change it in the future if we have a good reason to do it. If we do not, better to use the same mechanism for both systems.

**Comment by AlvaroVega** [comment]
IMHO current role extraction mechanism could not be applied to trust tokens.

**Comment by dmoranj** [comment]
Fixed in e34257f

**Comment by AlvaroVega** [comment]
It seems that works fine, allowing when is possible and denning when not. But if I wait 1 minute an retry the same op the result is different: 
```
[15:11][avega@rotary:~/tid/fiware/iotp-orchestrator/src/tests/api]
(task/log_format) curl -X GET  "http://127.0.0.1:1026/v1/contextEntities?details=on&limit=15&offset=0" -i -H "Accept: application/json"   -H "Fiware-Service: smartcity"   -H "Fiware-ServicePath: /basuras" -H "X-Auth-Token: 11b02d151d254778bc619937c737ee02"
HTTP/1.1 200 OK
X-Powered-By: Express
Unica-Correlator: 7a1ead33-cb18-4183-a70f-eebb1f020353
connection: close
content-length: 94
content-type: application/json
date: Fri, 03 Jul 2015 13:11:27 GMT

{
  "errorCode" : {
    "code" : "404",
    "reasonPhrase" : "No context element found"
  }
}
[15:11][avega@rotary:~/tid/fiware/iotp-orchestrator/src/tests/api]
(task/log_format) curl -X GET  "http://127.0.0.1:1026/v1/contextEntities?details=on&limit=15&offset=0" -i -H "Accept: application/json"   -H "Fiware-Service: smartcity"   -H "Fiware-ServicePath: /basuras" -H "X-Auth-Token: 11b02d151d254778bc619937c737ee02"
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Unica-Correlator: ac5a32d7-58da-4759-b26f-1f8dd6d16d84
Content-Type: application/json; charset=utf-8
Content-Length: 119
ETag: "-915272462"
Date: Fri, 03 Jul 2015 13:12:42 GMT
Connection: keep-alive

{
  "name": "ROLES_NOT_FOUND",
  "message": "No roles were found for the user token in the give subservice: /basuras"
}
```

Maybe a cache issue?

**Comment by dmoranj** [comment]
Sure, it seems to be. I'll check it and fix it monday morning.

**Comment by fgalan** [comment]
Be careful... this PR probably has been auto-closed when develop was removed, but it may have valuable commits. The solution is to merge develop into bug/trustTokenUsingTrustor and re-launch the PR againts master (a link to the old PR is usually a good idea, to review the comments there).

**Pull request closed without merging**
